# Generated by Django 3.0.7 on 2024-09-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='form_number',
            field=models.CharField(max_length=10),
        ),
    ]
